### ISSUE TITLE
Which Luwak is Solcolator using?

### ISSUE THREAD

**Issue by schrepfler** [SOLR4189/solcolator#2]
Looking at Luwak's project it says it's now part of the Apache Lucene library as of the v8.2.0 release. Is Solcolator using the integrated Luwak or the external Luwak?

**Comment by SOLR4189** [comment]
Solcolator uses the external Luwak. You can see it in pom.xml file

```
<dependency>
	    <groupId>com.github.flaxsearch</groupId>
	    <artifactId>luwak</artifactId>
	    <version>1.5.0</version>
	</dependency>
```

**Comment by schrepfler** [comment]
Thanks! Any advantage compared to the bundled one?

**Comment by SOLR4189** [comment]
I don't know. I didn't compare, but 1.5.0 version it's latest version in Maven. 
Maybe in bundle it's compatible with the latest LUCENE versions, because Luwak-1.5.0 doesn't work with Lucene 7.0.0+

Where can I see bundled Luwak versions? I didn't find.

**Comment by schrepfler** [comment]
If you open the Luwark project there's a notice to the Lucene 8.2 release notes which references https://issues.apache.org/jira/browse/LUCENE-8766

**Comment by SOLR4189** [comment]
Of course I saw it, but you ask me about bundled version. Where did you see it? What is a bundled version?

**Comment by schrepfler** [comment]
I was referring to the one which is now shipped with Lucene as the bundled one. Is there any benefit in using 1.5.0 compared to the classes which are now part of Lucene?

**Comment by SOLR4189** [comment]
Ok, I don't know.

**Comment by schrepfler** [comment]
Fair enough, in any case great work, I was following the original thread and was pleasantly surprised to see somebody took the initiative forward. Great stuff!

**Comment by SOLR4189** [comment]
Thank you. I was inspired by Luwak project and I like Solr/Lucene project (I work with it many years) :)
 I wrote Solcolator for the company, where I work (with small changed for company's business).
I hope one day  Solcolator (or something similar to Solcolator) will be a part of Solr project, like Percolator in ElasticSearch,
